steps:
  - label: "Tests (PHP 8.0)"
    command:
      - "PHP_VERSION=8.0 docker compose -f docker-compose.phpunit.yml run --rm --build wordpress_phpunit /app/bin/install-wp-tests.sh wordpress_test root '' host.containers.internal latest true"
      - "PHP_VERSION=8.0 docker compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit sh -c 'cd /app && phpunit'"
      - "PHP_VERSION=8.0 docker compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit sh -c 'cd /app-editions && phpunit'"
    plugins:
      - docker-compose#v5.4.0:
          config:
            - docker-compose.phpunit.yml

  - wait

  - label: "Tests (PHP 8.4)"
    command:
      - "PHP_VERSION=8.4 docker compose -f docker-compose.phpunit.yml run --rm --build wordpress_phpunit /app/bin/install-wp-tests.sh wordpress_test root '' host.containers.internal latest true"
      - "PHP_VERSION=8.4 docker compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit sh -c 'cd /app && phpunit'"
      - "PHP_VERSION=8.4 docker compose -f docker-compose.phpunit.yml run --rm wordpress_phpunit sh -c 'cd /app-editions && phpunit'"
    plugins:
      - docker-compose#v5.4.0:
          config:
            - docker-compose.phpunit.yml
